### PR TITLE
Feat: i18n

### PR DESCRIPTION
**Pull request by YubaC**
### Description

Add i18n support in `src/web/components/languages`.

### Motivation & Context

 🥇 This is the first feat of Archives!!

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/Yuba-Technology/Archives/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run format-and-lint`)_
- [x] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### Related issues

#12

### CODE REVIEW

**Comment by YubaC** [comment]
@CatilonyZhang Could you please review this PR?

**Comment by CatilonyZhang** [comment]
Very good contribution

**Review by CatilonyZhang — COMMENTED** [review]
very well

**Review by CatilonyZhang — APPROVED** [review]
go ahead!

**Pull request merged**
